apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: {{ .Values.spec.destination.server }}
  project: sre
  source:
    helm:
      valueFiles:
      - values.yaml
    path: values/eks-production/vault
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-vault-secrets-webhook
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: {{ .Values.spec.destination.server }}
  project: sre
  source:
    helm:
      valueFiles:
      - values.yaml
    path: values/eks-production/bank-vault-secrets-webhook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
