{{- if .Values.configmap.enable -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.serviceName }}
data:
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | squote }}
  {{- end }}
{{- end }}
