{{- if .Values.service.enable -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.serviceName }}
  name: {{ .Values.serviceName }}
spec:
  ports:
  - name: {{ .Values.service.name | default "http" }}
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol | default "TCP"}}
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ .Values.serviceName }}
  type: {{ .Values.service.type }}
{{- end }}
