{{- if .Values.serviceAccount.enable -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceName}}
  labels:
    app: {{ .Values.serviceName}}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
