aws-ebs-csi-driver:
  controller:
    affinity:
      nodeAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 1
          preference:
            matchExpressions:
            - key: eks.amazonaws.com/compute-type
              operator: NotIn
              values:
              - fargate
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - ebs-csi-controller
            topologyKey: kubernetes.io/hostname
          weight: 100
    replicaCount: 1
    tolerations: []
    serviceAccount:
      create: true
      name: aws-ebs-csi-driver
      annotations:
        eks.amazonaws.com/role-arn: arn:aws:iam::157329022736:role/aws-ebs-csi-driver
