vault:
  injector:
    enabled: true
    replicas: 3
    failurePolicy: Fail # https://github.com/hashicorp/vault-helm/issues/399 and https://github.com/hashicorp/vault-helm/issues/609
    namespaceSelector:
      matchLabels:
        sidecar-injector: enabled
    logLevel: "debug"
  server:
    logLevel: "debug"
    ha:
      enabled: true
      raft:
        enabled: true # doc https://www.vaultproject.io/docs/platform/k8s/helm/examples/ha-with-raft
        setNodeId: true
        config: |
          ui = true

          listener "tcp" {
            tls_disable = 1
            address = "[::]:8200"
            cluster_address = "[::]:8201"
          }

          service_registration "kubernetes" {}

          seal "awskms" {
            region     = "ap-southeast-1"
            kms_key_id = "05a9622b-ccba-496d-9cb1-f96eb68063fc"
          }

          storage "raft" {
            path        = "/vault/data"
          }

    dataStorage:
      enabled: true
      size: 20Gi
    serviceAccount:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::248666422610:role/vault"
    ingress:
      enabled: true
      ingressClassName: internal-nginx
      hosts:
        - host: vault-production.tk
      tls:
        - secretName: cert-secret
          hosts:
          - vault-production.tk
    updateStrategyType: "RollingUpdate"
  ui:
    enabled: true
