apiVersion: v2
name: observability

version: 2.6.1
appVersion: v2.1.0

dependencies:
  - name: prometheus
    version: "25.1.0"
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
  - name: grafana
    version: "6.60.*"
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
