prometheus:
  rbac:
    create: true
    ingress:
      enabled: false
  serverFiles:
    alerting_rules.yaml:
      groups:
        - name: KubernetesPodCrashLooping
          rules:
          - alert: KubernetesPodCrashLooping
            expr: kube_pod_container_status_restarts_total > 3
            for: 2m
            labels:
              severity: critical
            annotations:
              summary: Kubernetes pod crash looping (instance {{ $labels.instance }})
              description: "Pod {{ $labels.namespace }}/{{ $labels.pod }} is crash looping\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    prometheus.yml:
      rule_files:
        - /etc/config/recording_rules.yaml
        - /etc/config/alerting_rules.yaml
  alertmanager:
    enabled: true
    config:
      enabled: true
      global:
        resolve_timeout: 5m
      route:
        receiver: telegram_receiver
        group_wait: 10s
        repeat_interval: 5m
        routes:
          - receiver: telegram_receiver
            match:
              severity: critical
      receivers:
      - name: telegram_receiver
        telegram_configs:
        - api_url: 'https://api.telegram.org'
          bot_token: '6056517654:AAGpwDxUDDENvwk160h82ycNb5UZv6ae-As' # this shoule be masked
          chat_id: -1001938508004
  kube-state-metrics:
    enabled: true
  prometheus-node-exporter:
    enabled: true
  prometheus-pushgateway:
    enabled: true


curl -X POST \
     -H 'Content-Type: application/json' \
     -d '{"chat_id": "-1001938508004", "text": "This is a test from curl", "disable_notification": false}' \
     https://api.telegram.org/bot6056517654:AAGpwDxUDDENvwk160h82ycNb5UZv6ae-As/sendMessage
