spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: application
    cluster: eks-production
  source:
    repoURL: https://github.com/thienchuong/argocd-apps.git
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
applications:
  - podinfo
