apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: {{ .Values.spec.destination.server }}
  project: sre
  source:
    helm:
      valueFiles:
      - values.yaml
    path: values/{{ .Values.spec.destination.cluster }}/platform/vault
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 8 }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bank-vault-secrets-webhook
  namespace: argocd
spec:
  destination:
    namespace: vault
    server: {{ .Values.spec.destination.server }}
  project: sre
  source:
    helm:
      valueFiles:
      - values.yaml
    path: values/{{ .Values.spec.destination.cluster }}/platform/bank-vault-secrets-webhook
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
  syncPolicy:
    {{- toYaml .Values.spec.syncPolicy | nindent 8 }}
