apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: eks-external-secret
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: eks-secret-store
    kind: SecretStore
  target:
    name: eks-secret
  data:
  - secretKey: host
    remoteRef:
      key: secret-rotated-example20231011145213682700000001
      property: host
  - secretKey: password
    remoteRef:
      key: secret-rotated-example20231011145213682700000001
      property: password
