apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
  namespace: karpenter
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
    - key: karpenter.k8s.aws/instance-generation
      operator: Gt	
      values:	["2"]
    - key: "karpenter.k8s.aws/instance-category"
      operator: In
      values: [t]
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: default
  consolidation: 
    enabled: true
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
  namespace: karpenter
spec:
  subnetSelector:
    karpenter.sh/discovery: eks-production
  securityGroupSelector:
    karpenter.sh/discovery: eks-production
  tags:
    ec2:ResourceTag/karpenter.sh/discovery: eks-production
